//
// ModelResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Модель ответа на запрос списка персонажей. */
public struct ModelResponse: Codable, Hashable {

    public var info: ResponseInfo?
    /** Список персонажей */
    public var results: [ModelCharacter]?

    public init(info: ResponseInfo? = nil, results: [ModelCharacter]? = nil) {
        self.info = info
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case info
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(info, forKey: .info)
        try container.encodeIfPresent(results, forKey: .results)
    }
}

