//
// ModelCharacter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Модель персонажа из Rick and Morty */
public struct ModelCharacter: Codable, Hashable {

    /** Идентификатор персонажа */
    public var id: Int?
    /** Имя персонажа */
    public var name: String?
    /** Статус персонажа (жив/мертв) */
    public var status: String?
    /** Вид персонажа */
    public var species: String?
    /** Дополнительное описание вида персонажа */
    public var type: String?
    /** Пол персонажа */
    public var gender: String?
    public var origin: CharacterOrigin?
    public var location: CharacterLocation?
    /** URL изображения персонажа */
    public var image: String?
    /** Эпизоды, в которых появлялся персонаж */
    public var episode: [String]?
    /** URL на информацию о персонаже */
    public var url: String?
    /** Дата и время создания персонажа */
    public var created: Date?

    public init(id: Int? = nil, name: String? = nil, status: String? = nil, species: String? = nil, type: String? = nil, gender: String? = nil, origin: CharacterOrigin? = nil, location: CharacterLocation? = nil, image: String? = nil, episode: [String]? = nil, url: String? = nil, created: Date? = nil) {
        self.id = id
        self.name = name
        self.status = status
        self.species = species
        self.type = type
        self.gender = gender
        self.origin = origin
        self.location = location
        self.image = image
        self.episode = episode
        self.url = url
        self.created = created
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case status
        case species
        case type
        case gender
        case origin
        case location
        case image
        case episode
        case url
        case created
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(species, forKey: .species)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(gender, forKey: .gender)
        try container.encodeIfPresent(origin, forKey: .origin)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(episode, forKey: .episode)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(created, forKey: .created)
    }
}

